### ISSUE TITLE
rake public_uid:generate

### ISSUE THREAD

**Issue by ramzihemadou** [equivalent/public_uid#16]
cant generate uid for null value column

**Comment by jamespearson** [comment]
Agreed. Rails 5.2.2.1, the rake task does nothing..

Here is a trace: 
```
> rake public_uid:generate --trace

** Invoke public_uid:generate (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute public_uid:generate
```

**Comment by equivalent** [comment]
ok guys version [1.3.1](https://rubygems.org/gems/public_uid  ) released today with the fix 

here is the fx https://github.com/equivalent/public_uid/commit/b2ff39ace89ad614417d4580ed7500cd5c969df5

thank you for reporting this @jamespearson  @ramzihemadou  :+1:
